# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15.1
ARG APP_VERSION=""

FROM ghcr.io/daemonless/nginx-base:${BASE_VERSION}

ARG APP_VERSION
ARG UPSTREAM_URL="https://api.github.com/repos/linuxserver/Heimdall/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:80/daemonless-ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Heimdall" \
      org.opencontainers.image.description="An Application dashboard and launcher — organize all your web apps and services in one place." \
      org.opencontainers.image.source="https://github.com/daemonless/heimdall" \
      org.opencontainers.image.url="https://heimdall.site/" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="80" \
      io.daemonless.volumes="/config" \
      io.daemonless.upstream-mode="source" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

ARG PACKAGES="php84 php84-dom php84-intl php84-opcache php84-pdo_sqlite php84-tokenizer \
    php84-mbstring php84-xml php84-fileinfo php84-curl php84-ctype php84-zip php84-session php84-filter ca_root_nss"

# Install PHP runtime packages
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Fetch Heimdall release; fail loudly if the version/tarball can't be resolved
# (a silent failure would ship an empty /app/www -> "File not found").
# Auth via HTTP_AUTH (base64 header), NOT a token-in-URL: GitHub's new stateless
# JWT GITHUB_TOKEN has dots and breaks fetch's URL parsing in the userinfo slot.
RUN --mount=type=secret,id=github_token \
    TOKEN=$(cat /run/secrets/github_token 2>/dev/null | tr -d '[:space:]' || true) && \
    APP_VER="${APP_VERSION:-$(HTTP_AUTH="${TOKEN:+basic:*:x-access-token:$TOKEN}" fetch -qo - "${UPSTREAM_URL}" 2>/dev/null | jq -r "${UPSTREAM_JQ}")}" && \
    if [ -z "$APP_VER" ] || [ "$APP_VER" = "null" ]; then \
        echo "ERROR: could not resolve Heimdall version from API (github_token bytes: $(printf %s "$TOKEN" | wc -c | tr -d ' '))" >&2; exit 1; \
    fi && \
    echo "Installing Heimdall ${APP_VER}" && \
    mkdir -p /app/www-tmp && \
    fetch -qo /tmp/heimdall.tar.gz "https://github.com/linuxserver/Heimdall/archive/refs/tags/${APP_VER}.tar.gz" && \
    tar -xzf /tmp/heimdall.tar.gz -C /app/www-tmp --strip-components=1 && \
    rm -f /tmp/heimdall.tar.gz && \
    test -f /app/www-tmp/public/index.php || { echo "ERROR: Heimdall extraction incomplete" >&2; exit 1; } && \
    echo "${APP_VER}" > /app/version

# Set up directories and permissions
RUN mkdir -p /config && \
    chown -R bsd:bsd /config /app

# Copy s6 service scripts and defaults
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/cont-init.d/* /etc/services.d/*/run 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 80

# --- Volumes (Injected by Generator) ---
VOLUME /config