# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

# syntax=docker/dockerfile:1
ARG BASE_VERSION=15
ARG APP_VERSION=""

FROM ghcr.io/daemonless/nginx-base:${BASE_VERSION}

ARG APP_VERSION
ARG UPSTREAM_URL="https://api.github.com/repos/linuxserver/Heimdall/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:80/daemonless-ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="Heimdall" \
      org.opencontainers.image.description="An Application dashboard and launcher — organize all your web apps and services in one place." \
      org.opencontainers.image.source="https://github.com/daemonless/heimdall" \
      org.opencontainers.image.url="https://heimdall.site/" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="80" \
      io.daemonless.volumes="/config" \
      io.daemonless.upstream-mode="source" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}"

ARG PACKAGES="php84 php84-dom php84-intl php84-opcache php84-pdo_sqlite php84-tokenizer \
    php84-mbstring php84-xml php84-fileinfo php84-curl php84-ctype php84-zip php84-session php84-filter ca_root_nss"

# Install PHP runtime packages
RUN pkg update && \
    pkg install -y ${PACKAGES} && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Fetch Heimdall release (tarball includes vendor/ and pre-built frontend assets)
RUN --mount=type=secret,id=github_token \
    TOKEN=$(cat /run/secrets/github_token 2>/dev/null || true) && \
    if [ -n "$TOKEN" ]; then \
        API_URL="https://x-access-token:${TOKEN}@api.github.com/repos/linuxserver/Heimdall/releases/latest"; \
    else \
        API_URL="${UPSTREAM_URL}"; \
    fi && \
    APP_VER="${APP_VERSION:-$(fetch -qo - "$API_URL" | jq -r "${UPSTREAM_JQ}")}" && \
    mkdir -p /app/www-tmp && \
    fetch -qo - "https://github.com/linuxserver/Heimdall/archive/refs/tags/${APP_VER}.tar.gz" | \
        tar -xz -C /app/www-tmp --strip-components=1 && \
    echo "${APP_VER}" > /app/version

# Set up directories and permissions
RUN mkdir -p /config && \
    chown -R bsd:bsd /config /app

# Copy s6 service scripts and defaults
COPY root/ /

# Make scripts executable
RUN chmod +x /etc/cont-init.d/* /etc/services.d/*/run 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 80

# --- Volumes (Injected by Generator) ---
VOLUME /config